targets:
  $default:
    builders:
      slang_build_runner:
        options:
          namespaces: true
          output_file_name: translations.g.dart
          string_interpolation: braces
          translation_overrides: true
          fallback_strategy: base_locale
