builders:
  failures:
    import: "package:failures_builder/failures_builder.dart"
    builder_factories: ["failures"]
    build_extensions: { ".dart": ["failures.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
